# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-1-us-east-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: 6543
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.osbjaeilalkaosceigsc
      - key: DB_POSTGRESDB_PASSWORD
        value: fadlksajflashfhladsmfhlashlfjdsafasdf11BB
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: false
